// Copies the website's wording (kasa-i18n.js) for the screens the app shares with
// kasa.html into src/siteText.ts, so both say the same thing in en/bn/hi.
// Run from mobile/: node scripts/site-text.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import vm from 'node:vm';

const ctx = { window: {} };
vm.runInNewContext(readFileSync(new URL('../../kasa-i18n.js', import.meta.url), 'utf8'), ctx);
const I18N = ctx.window.KASA_I18N;

const KEEP = /^(cat_|waste_|igrp_|issue_note_|issue_none|issue_search_ph|tl_|ev_|rate_|dk_|pn_|seen_|sheet_|act_|reply_title|reply_note|head_|chip_pending|wk_|ad_|fd_|sn_|sr_|pd_|sc_loc_ok|sev_(minor|severe|critical)$|stat_people|stat_days_|stat_type|nb_|held_|rej_|cap_|flag_done|flag_dup|share_text|pl_share|photo_extra|foot_|ago_|dur_|acc_ward$|acc_block$|acc_gp$|acc_unknown$)/;

const out = {};
for (const lang of ['en', 'bn', 'hi']) {
  out[lang] = Object.fromEntries(Object.entries(I18N[lang]).filter(([k]) => KEEP.test(k)).sort(([a], [b]) => a.localeCompare(b)));
}
writeFileSync(new URL('../src/siteText.ts', import.meta.url),
  `// Generated by scripts/site-text.mjs from kasa-i18n.js. Do not edit by hand.\n` +
  `export const SITE: Record<'en' | 'bn' | 'hi', Record<string, string>> = ${JSON.stringify(out, null, 1)};\n`);
console.log(Object.fromEntries(Object.entries(out).map(([l, d]) => [l, Object.keys(d).length])));
