#!/usr/bin/env python3
"""West Bengal district outlines for reports outside any mapped ward.

Source: LGD_Districts.parquet from https://github.com/yashveeeeeeer/india-geodata
(release "admin", CC0), the Local Government Directory's district boundaries.
Download it, then run:  python3 tools/build-districts.py LGD_Districts.parquet

Writes places/wb_districts.geojson and the district rows in
supabase/migrations/20260928120000_kasa_wb_districts.sql (between the markers).
Purulia is left out: its own blocks, wards and panchayats already cover it.
Needs: pip install duckdb shapely
"""
import json, re, sys
import duckdb
from shapely import wkb
from shapely.geometry import mapping

TOL = 0.002          # ~200 m; the outlines are approximate anyway
NAMES = {            # LGD spelling -> the name people use
  '24 Paraganas North': 'North 24 Parganas', '24 Paraganas South': 'South 24 Parganas',
  'Coochbehar': 'Cooch Behar', 'Dinajpur Dakshin': 'Dakshin Dinajpur', 'Dinajpur Uttar': 'Uttar Dinajpur',
  'Maldah': 'Malda', 'Medinipur East': 'Purba Medinipur', 'Medinipur West': 'Paschim Medinipur',
}
MIG = 'supabase/migrations/20260928120000_kasa_wb_districts.sql'
START = '-- ── District rows: generated by tools/build-districts.py, do not edit by hand ──'
END = '-- ── end of district rows ──'

def slug(n): return re.sub(r'[^a-z0-9]+', '-', n.lower()).strip('-')
def rnd(c): return [rnd(x) for x in c] if isinstance(c[0], (list, tuple)) else [round(c[0], 4), round(c[1], 4)]

con = duckdb.connect(); con.sql('install spatial; load spatial')
rows = con.sql(f"select dtname, dist_lgd, st_aswkb(geometry) from '{sys.argv[1]}' "
               "where stname ilike 'west bengal' and dtname <> 'Purulia' order by dtname").fetchall()
feats, sql = [], []
for name, lgd, g in rows:
    name = NAMES.get(name, name)
    geom = wkb.loads(bytes(g)).simplify(TOL, preserve_topology=True)
    m = mapping(geom)
    polys = [m['coordinates']] if m['type'] == 'Polygon' else list(m['coordinates'])
    polys = rnd([[list(r) for r in p] for p in polys])
    feats.append({'type': 'Feature', 'properties': {'district': name, 'slug': slug(name), 'lgd': lgd},
                  'geometry': {'type': 'MultiPolygon', 'coordinates': polys}})
    x0, y0, x1, y1 = geom.bounds
    sql.append(f"('district:{slug(name)}', 'district', '{name}', null, {y0:.4f}, {y1:.4f}, {x0:.4f}, {x1:.4f}, "
               f"'{json.dumps(polys, separators=(',', ':'))}'::jsonb, '{slug(name)}')")
json.dump({'type': 'FeatureCollection', 'features': feats}, open('places/wb_districts.geojson', 'w'), separators=(',', ':'))
s = open(MIG).read()
a, b = s.index(START) + len(START), s.index(END)
body = ("\ndelete from kasa_private.areas where kind = 'district';\n"
        "insert into kasa_private.areas (id, kind, name, ward_no, min_lat, max_lat, min_lng, max_lng, polygons, parent) values\n"
        + ',\n'.join(sql) + ';\n')
open(MIG, 'w').write(s[:a] + body + s[b:])
print(len(feats), 'districts')
