#!/usr/bin/env python3
"""Every West Bengal municipality and corporation on the report map (outside Kolkata and Purulia).

    python3 -m pip install geopandas pyarrow shapely
    python3 tools/build-wb-towns.py DIR

DIR holds WB_AMRUT_ULBs.parquet and WB_AMRUT_Wards.parquet from the urban/boundaries release of
github.com/yashveeeeeeer/india-geodata (CC0): the West Bengal AMRUT GIS town limits and ward
maps (Ministry of Housing and Urban Affairs). The list of towns and their ward counts is the
State Election Commission's 2022 result table on Wikipedia ("2022 West Bengal local elections");
a town with no open outline is placed at its Wikipedia article's coordinates.

Checked September 2026: OpenStreetMap has no municipal limits in West Bengal (towns are points,
"county" relations are blocks), SBM's ULB layer has no West Bengal towns, and SBM's West Bengal
wards are the same AMRUT maps.

Writes
- places/wb_towns.geojson: an outline (AMRUT) or a point (Wikipedia) per town, with its
  ward count and how many wards are mapped. kasa.js draws it and opens the town card.
- supabase/migrations/20260930160000_kasa_wb_towns.sql, the rows between the markers: the
  AMRUT towns with a full ward map become places (same as a town sent in on add-town.html),
  so a report there is filed under the town and ward.
Siliguri's AMRUT map has 4 of its 47 wards, so it gets the outline only.
"""
import json, re, sys, time, urllib.parse, urllib.request
from pathlib import Path

import geopandas as gpd
import shapely
from shapely.geometry import mapping, shape

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(sys.argv[1] if len(sys.argv) > 1 else '.')
UA = {'User-Agent': 'ParishkarBengal/1.0 (civic map; https://github.com/archiboltmusk/Purulia)'}
SEC_PAGE = '2022 West Bengal local elections'
AMRUT_SRC = 'https://github.com/yashveeeeeeer/india-geodata/releases/tag/urban%2Fboundaries'
MIGRATION = ROOT / 'supabase/migrations/20260930160000_kasa_wb_towns.sql'
MARK, END = '-- ── Town rows: generated by tools/build-wb-towns.py, do not edit by hand ──\n', '-- ── end of town rows ──\n'
TOL = 0.00004                     # degrees, about 4 m (wards simplified together, so no gaps)

# SEC table name (without "Municipality") -> the town's usual name / Wikipedia article.
ALIAS = {'Murshidabad Sadar': 'Murshidabad', 'Tamralipta': 'Tamluk', 'Kanthi': 'Contai', 'Sreerampur': 'Serampore',
         'Hooghly–Chunchura': 'Chinsurah', 'Guskhara': 'Guskara', 'Medinipur': 'Midnapore', 'Baharampur': 'Berhampore',
         'Bardhaman': 'Bardhaman', 'Jiaganj–Azimganj': 'Jiaganj Azimganj', 'Rajpur–Sonarpur': 'Rajpur Sonarpur',
         'Ashoknagar–Kalyangarh': 'Ashoknagar Kalyangarh', 'Joynagar–Majilpur': 'Jaynagar Majilpur',
         'Uttarpara': 'Uttarpara Kotrung', 'Mal': 'Malbazar', 'Khardaha': 'Khardaha'}
ARTICLE = {'Murshidabad': 'Murshidabad', 'Islampur': 'Islampur, Uttar Dinajpur', 'Kandi': 'Kandi, Murshidabad', 'Bhadreswar': 'Bhadreswar, Hooghly'}
# AMRUT's names -> the same town above.
AMRUT_NAME = {'Burdwan': 'Bardhaman', 'Hooghly-Chinsurah': 'Chinsurah', 'Chandananagar': 'Chandannagar',
              'Uttarpara-Kotrung': 'Uttarpara Kotrung', 'Khardah': 'Khardaha', 'Ashokenagar Kalyangarh': 'Ashoknagar Kalyangarh',
              'Rajpur-Sonarpur': 'Rajpur Sonarpur', 'Nabadiganta Industrial Township Authority': 'Nabadiganta'}
# AMRUT towns not in the 2022 table (elected separately, or not elected).
EXTRA_BODY = {'Raiganj': 'Raiganj Municipality', 'Howrah': 'Howrah Municipal Corporation', 'Bally': 'Bally Municipality',
              'Durgapur': 'Durgapur Municipal Corporation', 'Haldia': 'Haldia Municipality',
              'New Town': 'New Town Kolkata Development Authority', 'Nabadiganta': 'Nabadiganta Industrial Township Authority'}
NO_WARDS = {'New Town', 'Nabadiganta'}   # development authorities, no elected wards
SKIP = {'Purulia', 'Jhalda', 'Raghunathpur'}   # Purulia district has its own wards and outlines


def get(url):
    for i in range(6):
        try:
            return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60).read().decode()
        except urllib.error.HTTPError as e:
            if e.code != 429: raise
            time.sleep(5 * (i + 1))
    raise SystemExit('Wikipedia keeps saying 429')


def short(n):
    t = re.sub(r'\s+(Municipal Corporation|Municipality|Notified Area Authority)$', '', n).strip()
    return ALIAS.get(t, t)


def sec_towns():
    """[{name, body, wards}] from the SEC 2022 corporation and municipality tables."""
    t = get('https://en.wikipedia.org/w/index.php?action=raw&title=' + urllib.parse.quote(SEC_PAGE.replace(' ', '_')))
    lines = [l.strip() for l in t[t.index('===Corporation wise result'):].split('\n')]
    out = []
    for i, l in enumerate(lines[:-1]):
        m = re.match(r"\|\s*'''(\d+)'''", lines[i + 1])
        if not m or not l.startswith('|') or l.startswith('|-') or 'district' in l: continue
        L = re.findall(r'\[\[([^\]|]+)(?:\|([^\]]+))?\]\]', l)
        body = (L[0][1] or L[0][0]) if L else l.lstrip('|').strip()
        body = body.replace('Murshidbad', 'Murshidabad')   # typo in the table
        out.append({'name': short(body), 'body': body, 'wards': int(m.group(1))})
    return out


def coords(names):
    """Town -> [lng, lat] from its Wikipedia article (inside West Bengal only)."""
    res = {}
    for variant in ('{}, West Bengal', '{}', '{}, India'):
        todo = [n for n in names if n not in res]
        for i in range(0, len(todo), 40):
            titles = [ARTICLE.get(n) or variant.format(n) for n in todo[i:i + 40]]
            q = urllib.parse.urlencode({'action': 'query', 'prop': 'coordinates', 'titles': '|'.join(titles),
                                        'redirects': 1, 'format': 'json', 'colimit': 'max'})
            d = json.loads(get('https://en.wikipedia.org/w/api.php?' + q))['query']
            time.sleep(2)
            to = {r['from']: r['to'] for k in ('normalized', 'redirects') for r in d.get(k, [])}
            c = {p['title']: p.get('coordinates') for p in d['pages'].values()}
            for n, t in zip(todo[i:i + 40], titles):
                while t in to: t = to[t]
                p = (c.get(t) or [None])[0]
                if p and 21.4 < p['lat'] < 27.3 and 85.8 < p['lon'] < 89.95:
                    res[n] = ([round(p['lon'], 4), round(p['lat'], 4)], 'https://en.wikipedia.org/wiki/' + urllib.parse.quote(t.replace(' ', '_')))
    return res


def rnd(c): return [rnd(x) for x in c] if isinstance(c[0], (list, tuple)) else [round(c[0], 5), round(c[1], 5)]
def slug(n): return re.sub(r'[^a-z0-9]+', '-', n.lower()).strip('-')
def sq(s): return "'" + str(s).replace("'", "''") + "'" if s is not None else 'null'


def main():
    districts = json.loads((ROOT / 'places/wb_districts.geojson').read_text())['features']
    dshapes = [(f['properties'], shape(f['geometry'])) for f in districts]
    def district_of(pt):
        p = shapely.Point(pt)
        return next((d for d, g in dshapes if g.contains(p)), None) or min(dshapes, key=lambda x: x[1].distance(p))[0]

    sec = {t['name']: t for t in sec_towns()}
    ulbs = gpd.read_parquet(SRC / 'WB_AMRUT_ULBs.parquet')
    wards = gpd.read_parquet(SRC / 'WB_AMRUT_Wards.parquet')
    towns = {}
    for _, u in ulbs.iterrows():
        name = AMRUT_NAME.get(u.Name, u.Name)
        if name in SKIP: continue
        body = sec[name]['body'] if name in sec else EXTRA_BODY.get(name)
        if not body: print('not in the SEC table:', name); continue
        w = wards[wards.ULB_Code == u.ULB_Code].copy()
        w['n'] = w.Ward_No.astype(int)
        w = w[w.n > 0].dissolve('n').reset_index()          # ward 0 is unassigned land; split wards come as parts
        total = 0 if name in NO_WARDS else sec.get(name, {}).get('wards')
        full = len(w) and (total is None or len(w) >= total * 0.9)
        towns[name] = {'name': name, 'body': body, 'wards': total, 'geom': u.geometry, 'ulb': u.ULB_Code,
                       'ward_geoms': list(zip(w.n, w.geometry)) if full else [], 'src': 'amrut'}
    pts = coords([n for n in sec if n not in towns and n not in SKIP])
    for n, t in sec.items():
        if n in towns or n in SKIP: continue
        if n not in pts: print('no coordinates, left out:', n); continue
        towns[n] = {'name': n, 'body': t['body'], 'wards': t['wards'], 'point': pts[n][0], 'article': pts[n][1],
                    'ward_geoms': [], 'src': 'wikipedia'}

    feats, rows, places = [], [], []
    for n in sorted(towns):
        t = towns[n]
        s = slug(n)
        if 'geom' in t:
            g = shapely.make_valid(t['geom']).simplify(0.0001, preserve_topology=True)
            geom, c = mapping(g), g.representative_point()
            d = district_of((c.x, c.y))
        else:
            geom, d = {'type': 'Point', 'coordinates': t['point']}, district_of(t['point'])
        props = {'slug': s, 'name': n, 'body': t['body'], 'district': d['slug'], 'wards': t['wards'],
                 'mapped': len(t['ward_geoms']), 'src': t['src']}
        if t.get('article'): props['article'] = t['article']
        f = {'type': 'Feature', 'properties': props, 'geometry': {'type': geom['type'], 'coordinates': rnd(geom['coordinates'])}}
        if geom['type'] != 'Point':
            b = shape(f['geometry']).bounds
            f['bbox'] = [round(x, 5) for x in b]
        feats.append(f)
        if not t['ward_geoms']: continue
        simple = shapely.coverage_simplify([shapely.make_valid(g) for _, g in t['ward_geoms']], TOL)
        for (no, _), g in zip(t['ward_geoms'], simple):
            polys = [g] if g.geom_type == 'Polygon' else [p for p in getattr(g, 'geoms', []) if p.geom_type == 'Polygon']
            mp = [rnd(mapping(p)['coordinates']) for p in polys if p.area > 1e-9]
            x0, y0, x1, y1 = shapely.MultiPolygon(polys).bounds
            rows.append(f"('place_ward:{s}:{no}', 'place_ward', 'Ward {no}', {no}, {y0:.6f}, {y1:.6f}, {x0:.6f}, {x1:.6f}, "
                        f"'{json.dumps(mp, separators=(',', ':'))}'::jsonb, '{s}')")
        body_type = 'municipality'
        places.append(f"({sq(s)}, {sq(n)}, {sq(t['body'])}, '{body_type}', null, {len(t['ward_geoms'])}, "
                      f"{t['wards'] if t['wards'] else 'null'}, {sq('West Bengal AMRUT GIS ward map (MoHUA), via india-geodata: ' + AMRUT_SRC)}, "
                      f"'CC0', {sq(d['district'])}, 'live', false)")

    out = {'type': 'FeatureCollection',
           'attribution': 'Town limits and wards: West Bengal AMRUT GIS (MoHUA), via india-geodata (CC0). '
                          'Towns and ward counts: State Election Commission 2022 results, via Wikipedia.',
           'sources': {'amrut': AMRUT_SRC, 'sec': 'https://en.wikipedia.org/wiki/' + SEC_PAGE.replace(' ', '_')},
           'features': feats}
    (ROOT / 'places/wb_towns.geojson').write_text(json.dumps(out, separators=(',', ':'), ensure_ascii=False))

    slugs = ', '.join(sq(slug(n)) for n in sorted(towns) if towns[n]['ward_geoms'])
    sql = (MARK +
           'insert into kasa_private.places (slug, name, body, body_type, complaint_url, wards_mapped, wards_total, source, licence,\n'
           '                                 district, status, community) values\n' + ',\n'.join(places) + '\n'
           'on conflict (slug) do nothing;\n'
           f"delete from kasa_private.areas where kind = 'place_ward' and parent in ({slugs})\n"
           f"  and parent in (select slug from kasa_private.places where not community);\n"
           'insert into kasa_private.areas (id, kind, name, ward_no, min_lat, max_lat, min_lng, max_lng, polygons, parent)\n'
           'select v.* from (values\n' + ',\n'.join(rows) + '\n'
           ') v(id, kind, name, ward_no, min_lat, max_lat, min_lng, max_lng, polygons, parent)\n'
           'where v.parent in (select slug from kasa_private.places where not community)\n'
           'on conflict (id) do nothing;\n' + END)
    text = MIGRATION.read_text()
    MIGRATION.write_text(text[:text.index(MARK)] + sql + text[text.index(END) + len(END):])
    print(len(feats), 'towns,', len(places), 'with ward maps,', len(rows), 'wards')


if __name__ == '__main__':
    main()
