#!/usr/bin/env python3
"""Turns the public boundary files into SQL for kasa_private.areas.

    python3 tools/build-areas.py > /tmp/areas.sql

Inputs (repo root): purulia_blocks.geojson (20 CD blocks, from OpenStreetMap)
and purulia_wards.geojson (Purulia municipality wards). Ward outlines are
simplified to about 5 m; block outlines are already simplified.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def dp(points, tol):
    """Douglas-Peucker on a ring (keeps both ends)."""
    if len(points) < 4:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = (dx * dx + dy * dy) ** 0.5
    best, idx = 0.0, 0
    for i in range(1, len(points) - 1):
        px, py = points[i]
        d = abs(dy * px - dx * py + x2 * y1 - y2 * x1) / norm if norm else ((px - x1) ** 2 + (py - y1) ** 2) ** 0.5
        if d > best:
            best, idx = d, i
    if best <= tol:
        return [points[0], points[-1]]
    return dp(points[:idx + 1], tol)[:-1] + dp(points[idx:], tol)


def polygons(geom):
    return geom['coordinates'] if geom['type'] == 'MultiPolygon' else [geom['coordinates']]


def ring_sql(poly, tol=None):
    rings = []
    for ring in poly:
        r = dp(ring, tol) if tol else ring
        if len(r) >= 4:
            rings.append([[round(x, 5), round(y, 5)] for x, y in r])
    return rings


def bbox(polys):
    xs = [p[0] for poly in polys for ring in poly for p in ring]
    ys = [p[1] for poly in polys for ring in poly for p in ring]
    return min(ys), max(ys), min(xs), max(xs)


def q(s):
    return "'" + s.replace("'", "''") + "'"


rows = []
for f in json.loads((ROOT / 'purulia_blocks.geojson').read_text())['features']:
    polys = [ring_sql(p) for p in polygons(f['geometry'])]
    name = f['properties']['block']
    rows.append(('block', 'block:' + name.lower().replace(' ', '-'), name, None, polys))
for f in json.loads((ROOT / 'purulia_wards.geojson').read_text())['features']:
    polys = [ring_sql(p, 0.00005) for p in polygons(f['geometry'])]
    ward = int(str(f['properties']['ward']))
    rows.append(('ward', f'ward:purulia-{ward}', f'Ward {ward}', ward, polys))

out = sys.stdout
out.write('-- Generated by tools/build-areas.py. Do not edit by hand.\n')
out.write('insert into kasa_private.areas (id, kind, name, ward_no, min_lat, max_lat, min_lng, max_lng, polygons) values\n')
vals = []
for kind, aid, name, ward, polys in rows:
    a, b, c, d = bbox(polys)
    vals.append(f"  ({q(aid)}, {q(kind)}, {q(name)}, {ward if ward is not None else 'null'}, {a}, {b}, {c}, {d}, "
                f"{q(json.dumps(polys, separators=(',', ':')))}::jsonb)")
out.write(',\n'.join(vals))
out.write('\non conflict (id) do update set kind = excluded.kind, name = excluded.name, ward_no = excluded.ward_no,\n'
          '  min_lat = excluded.min_lat, max_lat = excluded.max_lat, min_lng = excluded.min_lng, max_lng = excluded.max_lng,\n'
          '  polygons = excluded.polygons;\n')
