#!/usr/bin/env python3
"""Builds places/<slug>_wards.geojson and the area rows in
supabase/migrations/20260928090000_kasa_places.sql for West Bengal places
outside Purulia that have an open, detailed ward map.

    python3 -m pip install shapely
    python3 tools/build-places.py DIR

DIR is a clone of github.com/datameet/Municipal_Spatial_Data (Kolkata/kolkata.geojson:
141 Kolkata Municipal Corporation wards, CC BY-SA 2.5 IN; wards 142-144, added
in 2015, are not in it). Outlines are kept at full detail (63,614 points), rounded to 6 decimals.

Checked September 2026 and skipped for lack of an open ward map: every other
West Bengal municipality and corporation (OpenStreetMap has no ward boundaries
for them, and DataMeet has none).
"""
import json
import sys
from pathlib import Path

from shapely.geometry import mapping, shape
from shapely.validation import make_valid

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(sys.argv[1] if len(sys.argv) > 1 else '.').resolve()
SOURCE = ('DataMeet Municipal_Spatial_Data, Kolkata wards '
          '(https://github.com/datameet/Municipal_Spatial_Data/tree/master/Kolkata), CC BY-SA 2.5 IN')
MIGRATION = ROOT / 'supabase/migrations/20260928090000_kasa_places.sql'
MARK = '-- ── Area rows: generated by tools/build-places.py, do not edit by hand ──'


def rnd(c):
    if c and isinstance(c[0], (int, float)):
        return [round(c[0], 6), round(c[1], 6)]
    return [rnd(x) for x in c]


def main():
    src = json.loads((SRC / 'Kolkata/kolkata.geojson').read_text())
    feats = []
    for f in sorted(src['features'], key=lambda f: int(f['properties']['WARD'])):
        g = shape(f['geometry'])
        if not g.is_valid:
            g = make_valid(g)
        m = mapping(g)
        feats.append({'type': 'Feature', 'properties': {'ward': int(f['properties']['WARD'])},
                      'geometry': {'type': m['type'], 'coordinates': rnd(m['coordinates'])}})
    out = ROOT / 'places/kolkata_wards.geojson'
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps({'type': 'FeatureCollection', 'source': SOURCE, 'features': feats},
                              separators=(',', ':')))

    rows = []
    for f in feats:
        polys = f['geometry']['coordinates'] if f['geometry']['type'] == 'MultiPolygon' else [f['geometry']['coordinates']]
        pts = [p for poly in polys for p in poly[0]]
        w = f['properties']['ward']
        rows.append("('place_ward:kolkata:%d', 'place_ward', 'Ward %d', %d, %s, %s, %s, %s, '%s'::jsonb, 'kolkata')" % (
            w, w, w, min(p[1] for p in pts), max(p[1] for p in pts), min(p[0] for p in pts), max(p[0] for p in pts),
            json.dumps(polys, separators=(',', ':'))))
    sql = (MARK + '\ndelete from kasa_private.areas where kind = \'place_ward\' and parent = \'kolkata\';\n'
           'insert into kasa_private.areas (id, kind, name, ward_no, min_lat, max_lat, min_lng, max_lng, polygons, parent) values\n'
           + ',\n'.join(rows) + ';\n-- ── end of area rows ──\n')
    text = MIGRATION.read_text()
    start, end = text.index(MARK), text.index('-- ── end of area rows ──\n') + len('-- ── end of area rows ──\n')
    MIGRATION.write_text(text[:start] + sql + text[end:])
    print(len(feats), 'wards')


if __name__ == '__main__':
    main()
