#!/usr/bin/env node
// The site's version comes from changelog.html: v1.<release days>.<changes on the newest day>.
// Adding a line to the changelog bumps the last number; a new date bumps the middle one.
//
//   node tools/version.mjs          writes version.js
//   node tools/version.mjs --check  fails if version.js is out of date (CI)
//
// changelog.html labels each date with the same numbers, so the badge on the report map
// opens the right day.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('..', import.meta.url);
const html = readFileSync(new URL('changelog.html', root), 'utf8');
const done = html.slice(html.indexOf('id="done"'));
const days = [...done.matchAll(/<h2>([^<]*\d{4})<\/h2>\s*<ul>([\s\S]*?)<\/ul>/g)];
if (!days.length) throw new Error('changelog.html: no dated sections after id="done"');
const [, date, list] = days[0];
const version = `1.${days.length}.${(list.match(/<li>/g) || []).length}`;
const js = `// Generated by tools/version.mjs from changelog.html. Do not edit by hand.\nwindow.PARISHKAR_VERSION = { version: '${version}', date: '${date.trim()}' };\n`;
const file = fileURLToPath(new URL('version.js', root));

if (process.argv.includes('--check')){
  let now = '';
  try { now = readFileSync(file, 'utf8'); } catch (e) {}
  if (now !== js){
    console.error(`version.js is out of date: run node tools/version.mjs (expected v${version}).`);
    process.exit(1);
  }
  console.log(`version.js is v${version}`);
} else {
  writeFileSync(file, js);
  console.log(`v${version} (${date.trim()})`);
}
