-- ════════════════════════════════════════════════════════════════════════
-- PURULIA KASA — every report names its local body
--
-- Purulia district has three municipalities (Purulia, Jhalda, Raghunathpur)
-- and 170 gram panchayats. Until now a report outside Purulia town only got
-- its CD block, so a report inside Jhalda or Raghunathpur town was sent to a
-- gram panchayat. This adds:
--   * areas of kind 'town' (Jhalda, Raghunathpur; Survey of India outlines)
--     and 'gp' (170 gram panchayats; Local Government Directory outlines),
--     loaded by 20260928050100_kasa_local_body_areas.sql, generated by
--     tools/build-areas.py from purulia_towns.geojson and purulia_gps.geojson;
--   * locate() returning `body` (e.g. "Jhalda Municipality", "Nutandih") and
--     `body_type` ('municipality' | 'gram_panchayat');
--   * reports.local_body, and boundary_type set by the server, not the phone.
-- area_kind stays 'town' for Purulia's wards and 'rural' everywhere else, so
-- the ward, quorum and claim rules are unchanged.
-- ════════════════════════════════════════════════════════════════════════

alter table kasa_private.areas drop constraint if exists areas_kind_check;
alter table kasa_private.areas add constraint areas_kind_check check (kind in ('block', 'ward', 'town', 'gp'));
alter table kasa_private.areas add column if not exists parent text;   -- a gram panchayat's CD block

alter table public.reports add column if not exists local_body text;

create or replace function kasa_private.locate(p_lat double precision, p_lng double precision, p_ward integer default null)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare
  v_ward  integer;
  v_block text;
  v_town  text;
  v_gp    record;
  v_pad   double precision := kasa_private.cfg_num('town_ward_margin_m') / 111000.0;
begin
  if p_lat is null or p_lng is null then return null; end if;
  select a.ward_no into v_ward from kasa_private.areas a
  where a.kind = 'ward' and p_lat between a.min_lat and a.max_lat and p_lng between a.min_lng and a.max_lng
    and kasa_private.in_polygons(p_lat, p_lng, a.polygons)
  order by a.ward_no limit 1;
  if v_ward is not null then
    return jsonb_build_object('kind', 'town', 'ward', coalesce(p_ward, v_ward),
                              'body', 'Purulia Municipality', 'body_type', 'municipality');
  end if;
  if p_ward between 1 and 23 and exists (
      select 1 from kasa_private.areas a
      cross join lateral jsonb_array_elements(a.polygons) poly
      cross join lateral jsonb_array_elements(poly -> 0) pt
      where a.kind = 'ward'
        and p_lat between a.min_lat - v_pad and a.max_lat + v_pad and p_lng between a.min_lng - v_pad and a.max_lng + v_pad
        and kasa_private.distance_m(p_lat, p_lng, (pt ->> 1)::double precision, (pt ->> 0)::double precision)
            <= kasa_private.cfg_num('town_ward_margin_m')) then
    return jsonb_build_object('kind', 'town', 'ward', p_ward,
                              'body', 'Purulia Municipality', 'body_type', 'municipality');
  end if;
  select a.name into v_block from kasa_private.areas a
  where a.kind = 'block' and p_lat between a.min_lat and a.max_lat and p_lng between a.min_lng and a.max_lng
    and kasa_private.in_polygons(p_lat, p_lng, a.polygons)
  order by a.id limit 1;
  select a.name into v_town from kasa_private.areas a
  where a.kind = 'town' and p_lat between a.min_lat and a.max_lat and p_lng between a.min_lng and a.max_lng
    and kasa_private.in_polygons(p_lat, p_lng, a.polygons)
  order by a.id limit 1;
  if v_town is not null then
    return jsonb_build_object('kind', 'rural', 'block', v_block, 'body', v_town, 'body_type', 'municipality');
  end if;
  select a.name, a.parent into v_gp from kasa_private.areas a
  where a.kind = 'gp' and p_lat between a.min_lat and a.max_lat and p_lng between a.min_lng and a.max_lng
    and kasa_private.in_polygons(p_lat, p_lng, a.polygons)
  order by a.id limit 1;
  if v_gp.name is not null then
    return jsonb_build_object('kind', 'rural', 'block', coalesce(v_block, v_gp.parent),
                              'body', v_gp.name, 'body_type', 'gram_panchayat');
  end if;
  if v_block is not null then
    return jsonb_build_object('kind', 'rural', 'block', v_block, 'body_type', 'gram_panchayat');
  end if;
  return null;
end $$;
revoke all on function kasa_private.locate(double precision, double precision, integer) from public, anon, authenticated;

create or replace function kasa_private.set_report_area() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_loc jsonb := kasa_private.locate(new.lat, new.lng, new.ward_no);
begin
  new.area_kind     := v_loc ->> 'kind';
  new.block_name    := v_loc ->> 'block';
  new.local_body    := v_loc ->> 'body';
  new.boundary_type := coalesce(v_loc ->> 'body_type', new.boundary_type);
  return new;
end $$;

create or replace view public.kasa_public_reports as
select r.id,
       date_trunc('hour', r.created_at) as created_at,
       r.lat, r.lng, r.ward_no, r.category, r.severity, r.status, r.description, r.landmark, r.photo_url,
       coalesce(r.upvotes, 0) as upvotes, r.seen_on_site, coalesce(r.flags, 0) as flags, r.moderation_status,
       coalesce(r.is_duplicate, false) as is_duplicate, r.parent_report_id, r.recurrence_count, r.rejected_claims,
       date_trunc('hour', r.resolved_at) as resolved_at,
       r.resolved_photo_url, r.resolution_method, coalesce(r.sla_days, 7) as sla_days,
       (r.accuracy_m is not null) as gps_verified,
       c.id as claim_id, c.photo_url as claim_photo_url,
       date_trunc('hour', c.created_at) as claim_created_at,
       c.verify_count as claim_verify_count, c.dispute_count as claim_dispute_count,
       date_trunc('hour', c.quorum_reached_at) as claim_quorum_reached_at,
       date_trunc('hour', c.final_after + interval '59 minutes 59 seconds') as claim_finalize_after,
       round(c.distance_m::numeric) as claim_distance_m,
       r.rating_count, r.onsite_rating_count, r.authenticity_avg, r.severity_avg, r.neighbour_status, r.reply_count,
       c.needs_review as claim_needs_review,
       r.area_kind, r.block_name,
       (select (s.value #>> '{}')::integer from kasa_private.settings s
        where s.key = case when r.area_kind = 'rural' then 'rural_verify_quorum' else 'verify_quorum' end) as verify_needed,
       date_trunc('hour', c.reviewed_at) as claim_reviewed_at,
       r.boundary_type,
       r.waste_type,
       r.local_body
from public.reports r
left join kasa_private.claims c on c.id = r.claim_id
where r.moderation_status in ('approved', 'flagged');

revoke all on public.kasa_public_reports from public, anon, authenticated;
grant select on public.kasa_public_reports to anon, authenticated;

notify pgrst, 'reload schema';
